# Generated by Django 5.0.4 on 2024-04-18 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='libro',
            name='tipo',
        ),
        migrations.AddField(
            model_name='libro',
            name='ul_publicacion',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='libro',
            name='publicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='puntaje',
            name='fecha_calificacion',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='Librotipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toshokandesu.libro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toshokandesu.tipo')),
            ],
        ),
    ]
