# Generated by Django 5.0.4 on 2024-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0002_tipo_remove_libro_tipo_libro_ul_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
