# Generated by Django 5.0.4 on 2024-04-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0003_alter_libro_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
