# Generated by Django 5.0.4 on 2024-04-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0004_alter_autor_perfil_alter_usuario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='libroautor',
            name='descripcion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
