# Generated by Django 5.0.4 on 2024-04-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0005_libroautor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='idioma',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
