# Generated by Django 5.0.4 on 2024-04-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0006_libro_idioma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='capitulo',
        ),
        migrations.CreateModel(
            name='LibroCapitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capitulo', models.FloatField(blank=True, null=True)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toshokandesu.libro')),
            ],
        ),
    ]
