# Generated by Django 5.0.4 on 2024-04-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0007_remove_libro_capitulo_librocapitulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='ul_publicacion',
        ),
    ]
