# Generated by Django 5.0.4 on 2024-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toshokandesu', '0008_remove_libro_ul_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
